services:
  - type: web
    name: IlmBot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_SECRET_CODE
        sync: false
      - key: COLLEGE_NAME
        sync: false

