services:
  - type: web
    name: IlmBot-Admin
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python admin_bot/main.py"
    envVars:
      - key: BOT_TOKEN
        value: 8960756644:AAFMFPCF0ZUS_jkISVI_1WOTG4IIvVn7w-E
      - key: ADMIN_ID
        value: 7890430043
      - key: ADMIN_SECRET_CODE
        value: 771267

  - type: web
    name: IlmBot-Student
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python student_bot/main.py"
    envVars:
      - key: BOT_TOKEN
        value: 8724867533:AAE4mVFqmv8CA_FhVaxkdgUvnx4_Nuhk1uI
      - key: COLLEGE_NAME
        value: كلية الحاسبات وتقنية المعلومات

